# Generated by Django 5.1 on 2024-08-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=30)),
                ('numero', models.TextField(max_length=13)),
                ('senha', models.TextField(max_length=99)),
            ],
        ),
    ]
